config/routes.rb
Rails.application.routes.draw do
	get "/users/myuser" => 'users#myuser'
	get "/api" => 'application#api'
	get "/signin" => 'application#signin'
	resources :speeches, only: [:create, :show, :index, :destroy]
	resources :users, only: [ :new, :create]
	root 'speeches#sandbox'

end

app/models/speech.rb
class Speech < ActiveRecord::Base
	belongs_to :user
	validates(:name, presence:true, uniqueness: true)
	validates(:grammar, presence:true)

	def to_param
		self.name
	end

	def to_s
		self.name
	end

end

app/models/user.rb
require 'record_authenticate'
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

class User < ActiveRecord::Base
	validates(:shadow, presence:true, length: { minimum: 1})
	validates(:name, presence:true, length: { minimum: 4, maximum: 255}, uniqueness: { case_sensitive: false})
	has_many :speech
	credentials :name, :shadow
end

app/controllers/application_controller.rb
require 'base64'

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authentication_kiss
	authenticate_with_http_basic do |user,pass|
		@current_user = User.authenticate user, pass
	end

	unless (@current_user)
		@error = "Credentials required."
		realm = request.server_name
		headers["WWW-Authenticate"] = %(Basic realm="#{realm.gsub(/"/, "")}")
		render 'signin', status: 401
	end
	@current_user
  end

  def get_user
	  @current_user
  end

  def api
  end

  def signin
  end

end

app/controllers/speeches_controller.rb
require_dependency 'cicero'

class SpeechesController < ApplicationController
	before_filter :authentication_kiss, :only => [:destroy]

	def sandbox
		f = open("lib/greet.bnf")
		@grammar = ""
		f.each_line do |line|
			@grammar += line
		end
		@grammar_name = "Hello linguists"
	end

	def create
		@grammar = params[:grammar]
		@grammar_name = params[:name]
		cic = CicerO.build(@grammar)
		if cic
			if params[:save]
				authentication_kiss
				@user = get_user
				if @user
					@speech = Speech.new({name: @grammar_name, grammar: @grammar, user: @user})
					if cic && @speech.save
						redirect_to @speech
						return
					else
						@error = "grammar name is already in use"
						render "sandbox"
						return
					end
				end
			else
				@speech = "Cicero says"
				@words = cic.speak()
				render "sandbox"
				return
			end
		else
			@error = "grammar is not syntactically correct"
			render "sandbox"
			return
		end
	end

	def show
		@speech = Speech.find_by_name(params[:id])
		if @speech
			cic = CicerO.build(@speech.grammar)
			@words = cic.speak()
		else
			@error = "Fai cacare"
		end
	end

	def index
		@speaches = Speech.all
	end

	def destroy
		@s = Speech.find_by_name(params[:id])
		if @current_user.speech.include? @s
			Speech.destroy(@s)
			@info = "Speech destroyed"
		else
			@error = "Speech "+@s.to_s+" does not belong to you"
		end
		redirect_to url_for(controller: 'users', action: 'myuser') # @current_user	
	end
end

app/controllers/users_controller.rb
require_dependency 'record_authenticate'

class UsersController < ApplicationController
	before_filter :authentication_kiss, :except => [:new, :create]

	def new

	end
	
	def create
		shadow = params["password"]
		name = params["name"]
		@neo = User.new({name: name, shadow: shadow})

		if @neo.save
			redirect_to url_for(controller: 'users', action: 'myuser') 
		else
			@error = "Credentials not valid"
			render "new"
		end
	end

	def myuser
		@user = get_user
		if @user
			render "show"
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/speeches_helper.rb
module SpeechesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_header.html.erb
<title>Cicero</title>

<%= render 'menu' %>
<%= render 'messages' %>

app/views/application/_menu.html.erb
<ul>
	<li> <%= link_to "Sign up",  new_user_path %> </li>
	<li> <%= link_to "My speeches",  url_for(controller: 'users', action: 'myuser') %> </li>
	<li> <%= link_to "All speeches",  speeches_path %> </li>
	<li> <%= link_to "Sandbox", "/"  %></li>
	<li> <%= link_to "API" , "/api" %> </li>
</ul>
<hr>

app/views/application/_messages.html.erb
<% if @error %>
	<p id='error'>Error: <%= @error %> </p>
<% end %>

<% if @speech and @words %>
	<p id='speech'> <%= "#{@speech}: "+ @words %> </p>
<% end %>

<% if @info %>
	<p class=info> <%= @info %> </p>
<% end %>

app/views/application/api.html.erb
<%= render 'header' %>

<h2>API</h2>
<table>
	<tr>
		<td class=table_head>Description</td>
		<td class=table_head>URL</td>
		<td class=table_head>Parameters</td>
	</tr>
	<tr>
		<td>Get the list of all speeches</td>
		<td>GET /speeches</td>
		<td></td>
	</tr>
	<tr>
		<td>Create a new user</td>
		<td>POST /users</td>
		<td>mail, password</td>
	</tr>
	<tr>
		<td>Get the user's speech list</td>
		<td>GET /users/myuser</td>
		<td></td>
	</tr>
	<tr>
		<td>Create a new speech</td>
		<td>POST /speeches</td>
		<td>grammar_name, grammar, save</td>
	</tr>
	<tr>
		<td>Delete a speech</td>
		<td>DELETE /speeches/speech_name</td>
		<td></td>
	</tr>
	<tr>
		<td>Generate a random speech</td>
		<td>GET /speeches/speech_id</td>
		<td></td>
	</tr>
</table>

app/views/application/signin.html.erb
<%= render 'header' %>
<h2>Sign in</h2>

<a href=<%=url_for(controller: 'users', action: 'myuser')%> id=auth-form class="httpauth" onload="this.style.backgroundColor='#990000'">Login</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cicero</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/speeches/index.html.erb
<%= render 'header' %>

<% @speaches.each do |s| %>
	<%= link_to s, s %> by <span class='author'><%= s.user.name %></span>
<% end %>

app/views/speeches/sandbox.html.erb
<%= render 'header' %>

<%= form_tag( url_for(controller: "speeches", action: "create"), method: "post") do %>
	<p>
	<%= label_tag(:name, "Name") %><br>
	<%= text_field_tag(:name, @grammar_name) %>
	</p>
	<p>
	<%= label_tag(:grammar, "Grammar:") %><br>
	<%= text_area_tag(:grammar, @grammar) %>
	</p>

	<p>
	<%= submit_tag("Try it!", name: "trial") %>
	<%= submit_tag("Post it!", name: "save") %>
	</p>
<% end %>

app/views/speeches/show.html.erb
<%= render 'header' %>

<%= @talk %>

app/views/users/new.html.erb
<%= render 'header' %>

<%= form_tag("/users", method: "post") do %>
	  <p>
    <%= label_tag(:name, "Your nickname: ") %><br>
    <%= text_field_tag(:name) %>
  </p>
 
    <p>
      <%= label_tag(:password, "Password: ") %><br>
      <%= password_field_tag(:password) %>
    </p>
   
      <p>
        <%= submit_tag("Submit") %>
      </p>
<% end %>

app/views/users/show.html.erb
<%= render 'header' %>

<% if @user %>
	<p><%= @user.name %> </p>
	<table>
	<% @user.speech.each do |s| %>
		<tr>
			<td> <%= link_to s, s %> </td>
			<td> <%= link_to "delete", s, method: "delete"%> </td>
		</tr>
	<% end %>
	</table>
<% end %>